In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('Pizza Data.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 371 entries, 0 to 370
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Company     371 non-null    object
 1   Pizza Name  371 non-null    object
 2   Type        371 non-null    object
 3   Size        371 non-null    object
 4   Price       371 non-null    object
dtypes: object(5)
memory usage: 14.6+ KB

In [4]:
df.isnull().sum()

Company       0
Pizza Name    0
Type          0
Size          0
Price         0
dtype: int64

 df.isnull()

# Label Encoeder

In [5]:
from sklearn.preprocessing import LabelEncoder

In [6]:
Label_obj=LabelEncoder()

In [7]:
print(df)

            Company           Pizza Name              Type           Size  \
0    Domino's Pizza          Hand Tossed     Cheeses Pizza    Small (10")
1    Domino's Pizza          Hand Tossed     Cheeses Pizza   Medium (12")
2    Domino's Pizza          Hand Tossed     Cheeses Pizza    Large (14")
3    Domino's Pizza         Handmade Pan     Cheeses Pizza   Medium (12")
4    Domino's Pizza   Crunchy Thin Crust     Cheeses Pizza    Small (10")
..              ...                  ...               ...            ...
366     IMO's Pizza    BBQ Chicken Pizza  Specialty Pizzas  X Large (16")
367     IMO's Pizza  Egg-Ceptional Pizza  Specialty Pizzas    Small (10")
368     IMO's Pizza  Egg-Ceptional Pizza  Specialty Pizzas   Medium (12")
369     IMO's Pizza  Egg-Ceptional Pizza  Specialty Pizzas    Large (14")
370     IMO's Pizza  Egg-Ceptional Pizza  Specialty Pizzas  X Large (16")

       Price
0     $5.99
1     $7.99
2     $9.99
3     $7.99
4     $5.99
..       ...
366  $23.85
367  $11.80
368  $14.95
369  $18.65
370  $22.30

[371 rows x 5 columns]

In [8]:
df['Pizza Name']=Label_obj.fit_transform(df["Pizza Name"])

In [9]:
df['Pizza Name']

0      96
1      96
2      96
3      98
4      75
       ..
366    15
367    82
368    82
369    82
370    82
Name: Pizza Name, Length: 371, dtype: int32

In [10]:
df['Pizza Name'].head()

0    96
1    96
2    96
3    98
4    75
Name: Pizza Name, dtype: int32

In [11]:
#one way to search all column
"""for column in df.columns:
    if df[column].dtype ==np.number:
        continue
        df[column]=Label_obj.fit_transform(df[column])
"""

'for column in df.columns:\n    if df[column].dtype ==np.number:\n        continue\n        df[column]=Label_obj.fit_transform(df[column])\n'

In [12]:
df.head()

          Company  Pizza Name           Type          Size   Price
0  Domino's Pizza          96  Cheeses Pizza   Small (10")  $5.99
1  Domino's Pizza          96  Cheeses Pizza  Medium (12")  $7.99
2  Domino's Pizza          96  Cheeses Pizza   Large (14")  $9.99
3  Domino's Pizza          98  Cheeses Pizza  Medium (12")  $7.99
4  Domino's Pizza          75  Cheeses Pizza   Small (10")  $5.99

# Replace Function

In [13]:
df=pd.read_csv('Pizza Data.csv')

In [14]:
df.head(50)

,Company,Pizza Name,Type,Size,Price
0,Domino's Pizza,Hand Tossed,Cheeses Pizza,"Small (10"")",$5.99
1,Domino's Pizza,Hand Tossed,Cheeses Pizza,"Medium (12"")",$7.99
2,Domino's Pizza,Hand Tossed,Cheeses Pizza,"Large (14"")",$9.99
3,Domino's Pizza,Handmade Pan,Cheeses Pizza,"Medium (12"")",$7.99
4,Domino's Pizza,Crunchy Thin Crust,Cheeses Pizza,"Small (10"")",$5.99
5,Domino's Pizza,Crunchy Thin Crust,Cheeses Pizza,"Medium (12"")",$7.99
6,Domino's Pizza,Crunchy Thin Crust,Cheeses Pizza,"Large (14"")",$9.99
7,Domino's Pizza,Brooklyn Style,Cheeses Pizza,"Large (14"")",$9.99
8,Domino's Pizza,Brooklyn Style,Cheeses Pizza,"X-Large (16"")",$11.99
9,Domino's Pizza,Gluten Free Crust,Cheeses Pizza,"Small (10"")",$8.99
10,Domino's Pizza,Spinach & Feta (Hand Tossed or Thin Crust),Specialty Pizzas,"Small (10"")",$11.99
11,Domino's Pizza,"Spinach & Feta (Hand Tossed, Handmade Pan or T...",Specialty Pizzas,"Medium (12"")",$13.99
12,Domino's Pizza,"Spinach & Feta (Hand Tossed, Thin Crust or Bro...",Specialty Pizzas,"Large (14"")",$15.99
13,Domino's Pizza,Spinach & Feta (Brooklyn Style),Specialty Pizzas,"X-Large (16"")",$17.99
14,Domino's Pizza,Spinach & Feta (Gluten Free Crust),Specialty Pizzas,"Small (10"")",$14.99
15,Domino's Pizza,Wisconsin 6 Cheese (Hand Tossed or Thin Crust),Specialty Pizzas,"Small (10"")",$11.99
16,Domino's Pizza,"Wisconsin 6 Cheese (Hand Tossed, Handmade Pan ...",Specialty Pizzas,"Medium (12"")",$13.99
17,Domino's Pizza,"Wisconsin 6 Cheese (Hand Tossed, Thin Crust or...",Specialty Pizzas,"Large (14"")",$15.99
18,Domino's Pizza,Wisconsin 6 Cheese (Brooklyn Style),Specialty Pizzas,"X-Large (16"")",$17.99
19,Domino's Pizza,Wisconsin 6 Cheese (Gluten Free Crust),Specialty Pizzas,"Small (10"")",$14.99
20,Domino's Pizza,Honolulu Hawaiian (Hand Tossed or Thin Crust),Specialty Pizzas,"Small (10"")",$11.99
21,Domino's Pizza,"Honolulu Hawaiian (Hand Tossed, Handmade Pan o...",Specialty Pizzas,"Medium (12"")",$13.99
22,Domino's Pizza,"Honolulu Hawaiian (Hand Tossed, Thin Crust or ...",Specialty Pizzas,"Large (14"")",$15.99
23,Domino's Pizza,Honolulu Hawaiian (Brooklyn Style),Specialty Pizzas,"X-Large (16"")",$17.99
24,Domino's Pizza,Honolulu Hawaiian (Gluten Free Crust),Specialty Pizzas,"Small (10"")",$14.99
25,Domino's Pizza,Philly Cheese Steak (Hand Tossed or Thin Crust),Specialty Pizzas,"Small (10"")",$11.99
26,Domino's Pizza,"Philly Cheese Steak (Hand Tossed, Handmade Pan...",Specialty Pizzas,"Medium (12"")",$13.99
27,Domino's Pizza,"Philly Cheese Steak (Hand Tossed, Thin Crust o...",Specialty Pizzas,"Large (14"")",$15.99
28,Domino's Pizza,Philly Cheese Steak (Brooklyn Style),Specialty Pizzas,"X-Large (16"")",$17.99
29,Domino's Pizza,Philly Cheese Steak (Gluten Free Crust),Specialty Pizzas,"Small (10"")",$14.99
30,Domino's Pizza,Pacific Veggie (Hand Tossed or Thin Crust),Specialty Pizzas,"Small (10"")",$11.99
31,Domino's Pizza,"Pacific Veggie (Hand Tossed, Handmade Pan or T...",Specialty Pizzas,"Medium (12"")",$13.99
32,Domino's Pizza,"Pacific Veggie (Hand Tossed, Thin Crust or Bro...",Specialty Pizzas,"Large (14"")",$15.99
33,Domino's Pizza,Pacific Veggie (Brooklyn Style),Specialty Pizzas,"X-Large (16"")",$17.99
34,Domino's Pizza,Pacific Veggie (Gluten Free Crust),Specialty Pizzas,"Small (10"")",$14.99
35,Domino's Pizza,Cali Chicken Bacon Ranch™ (Hand Tossed or Thin...,Specialty Pizzas,"Small (10"")",$11.99
36,Domino's Pizza,"Cali Chicken Bacon Ranch™ (Hand Tossed, Handma...",Specialty Pizzas,"Medium (12"")",$13.99
37,Domino's Pizza,"Cali Chicken Bacon Ranch™ (Hand Tossed, Thin C...",Specialty Pizzas,"Large (14"")",$15.99
38,Domino's Pizza,Cali Chicken Bacon Ranch™ (Brooklyn Style),Specialty Pizzas,"X-Large (16"")",$17.99
39,Domino's Pizza,Cali Chicken Bacon Ranch™ (Gluten Free Crust),Specialty Pizzas,"Small (10"")",$14.99
40,Domino's Pizza,Fiery Hawaiian™ (Hand Tossed or Thin Crust),Specialty Pizzas,"Small (10"")",$11.99
41,Domino's Pizza,"Fiery Hawaiian™ (Hand Tossed, Handmade Pan or ...",Specialty Pizzas,"Medium (12"")",$13.99
42,Domino's Pizza,"Fiery Hawaiian™ (Hand Tossed, Thin Crust or Br...",Specialty Pizzas,"Large (14"")",$15.99
43,Domino's Pizza,Fiery Hawaiian™ (Brooklyn Style),Specialty Pizzas,"X-Large (16"")",$17.99
44,Domino's Pizza,Fiery Hawaiian™ (Gluten Free Crust),Specialty Pizzas,"Small (10"")",$14.99
45,Domino's Pizza,Buffalo Chicken (Hand Tossed or Thin Crust),Specialty Pizzas,"Small (10"")",$11.99
46,Domino's Pizza,"Buffalo Chicken (Hand Tossed, Handmade Pan or ...",Specialty Pizzas,"Medium (12"")",$13.99
47,Domino's Pizza,"Buffalo Chicken (Hand Tossed, Thin Crust or Br...",Specialty Pizzas,"Large (14"")",$15.99
48,Domino's Pizza,Buffalo Chicken (Brooklyn Style),Specialty Pizzas,"X-Large (16"")",$17.99
49,Domino's Pizza,Buffalo Chicken (Gluten Free Crust),Specialty Pizzas,"Small (10"")",$14.99

In [15]:
df.Size=df.Size.replace(['Small (10")','Medium (12")','Large (14")','X-Large (16")'],[1,2,3,4])

In [16]:
df.head(10)

          Company          Pizza Name           Type Size    Price
0  Domino's Pizza         Hand Tossed  Cheeses Pizza    1   $5.99
1  Domino's Pizza         Hand Tossed  Cheeses Pizza    2   $7.99
2  Domino's Pizza         Hand Tossed  Cheeses Pizza    3   $9.99
3  Domino's Pizza        Handmade Pan  Cheeses Pizza    2   $7.99
4  Domino's Pizza  Crunchy Thin Crust  Cheeses Pizza    1   $5.99
5  Domino's Pizza  Crunchy Thin Crust  Cheeses Pizza    2   $7.99
6  Domino's Pizza  Crunchy Thin Crust  Cheeses Pizza    3   $9.99
7  Domino's Pizza      Brooklyn Style  Cheeses Pizza    3   $9.99
8  Domino's Pizza      Brooklyn Style  Cheeses Pizza    4  $11.99
9  Domino's Pizza   Gluten Free Crust  Cheeses Pizza    1   $8.99

In [17]:
df.Size.value_counts()

Large            111
Medium            84
1                 39
2                 27
3                 24
Small             20
Jumbo             18
4                 16
Mini              14
Personal          12
X Large (16")      6
Name: Size, dtype: int64

In [18]:
df.Size.unique()

array([1, 2, 3, 4, 'Medium', 'Large', 'Personal', 'Small', 'Mini',
       'Jumbo', 'X Large (16")'], dtype=object)

# One Hot Encoding

In [19]:
df=pd.read_csv('Pizza Data.csv')
df.head()

          Company          Pizza Name           Type          Size   Price
0  Domino's Pizza         Hand Tossed  Cheeses Pizza   Small (10")  $5.99
1  Domino's Pizza         Hand Tossed  Cheeses Pizza  Medium (12")  $7.99
2  Domino's Pizza         Hand Tossed  Cheeses Pizza   Large (14")  $9.99
3  Domino's Pizza        Handmade Pan  Cheeses Pizza  Medium (12")  $7.99
4  Domino's Pizza  Crunchy Thin Crust  Cheeses Pizza   Small (10")  $5.99

In [20]:
dummy_ver=pd.get_dummies(df['Size'])

In [21]:
dummy_ver.head(50)

,Jumbo,Large,"Large (14"")",Medium,"Medium (12"")",Mini,Personal,Small,"Small (10"")","X Large (16"")","X-Large (16"")"
0,0,0,0,0,0,0,0,0,1,0,0
1,0,0,0,0,1,0,0,0,0,0,0
2,0,0,1,0,0,0,0,0,0,0,0
3,0,0,0,0,1,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,1,0,0
5,0,0,0,0,1,0,0,0,0,0,0
6,0,0,1,0,0,0,0,0,0,0,0
7,0,0,1,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,1
9,0,0,0,0,0,0,0,0,1,0,0
10,0,0,0,0,0,0,0,0,1,0,0
11,0,0,0,0,1,0,0,0,0,0,0
12,0,0,1,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,1
14,0,0,0,0,0,0,0,0,1,0,0
15,0,0,0,0,0,0,0,0,1,0,0
16,0,0,0,0,1,0,0,0,0,0,0
17,0,0,1,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,1
19,0,0,0,0,0,0,0,0,1,0,0
20,0,0,0,0,0,0,0,0,1,0,0
21,0,0,0,0,1,0,0,0,0,0,0
22,0,0,1,0,0,0,0,0,0,0,0
23,0,0,0,0,0,0,0,0,0,0,1
24,0,0,0,0,0,0,0,0,1,0,0
25,0,0,0,0,0,0,0,0,1,0,0
26,0,0,0,0,1,0,0,0,0,0,0
27,0,0,1,0,0,0,0,0,0,0,0
28,0,0,0,0,0,0,0,0,0,0,1
29,0,0,0,0,0,0,0,0,1,0,0
30,0,0,0,0,0,0,0,0,1,0,0
31,0,0,0,0,1,0,0,0,0,0,0
32,0,0,1,0,0,0,0,0,0,0,0
33,0,0,0,0,0,0,0,0,0,0,1
34,0,0,0,0,0,0,0,0,1,0,0
35,0,0,0,0,0,0,0,0,1,0,0
36,0,0,0,0,1,0,0,0,0,0,0
37,0,0,1,0,0,0,0,0,0,0,0
38,0,0,0,0,0,0,0,0,0,0,1
39,0,0,0,0,0,0,0,0,1,0,0
40,0,0,0,0,0,0,0,0,1,0,0
41,0,0,0,0,1,0,0,0,0,0,0
42,0,0,1,0,0,0,0,0,0,0,0
43,0,0,0,0,0,0,0,0,0,0,1
44,0,0,0,0,0,0,0,0,1,0,0
45,0,0,0,0,0,0,0,0,1,0,0
46,0,0,0,0,1,0,0,0,0,0,0
47,0,0,1,0,0,0,0,0,0,0,0
48,0,0,0,0,0,0,0,0,0,0,1
49,0,0,0,0,0,0,0,0,1,0,0

In [22]:
dummy=pd.get_dummies(df['Size'],drop_first=True)

In [23]:
df=df.drop("Size",axis=1)

In [24]:
df.head()

          Company          Pizza Name           Type   Price
0  Domino's Pizza         Hand Tossed  Cheeses Pizza  $5.99
1  Domino's Pizza         Hand Tossed  Cheeses Pizza  $7.99
2  Domino's Pizza         Hand Tossed  Cheeses Pizza  $9.99
3  Domino's Pizza        Handmade Pan  Cheeses Pizza  $7.99
4  Domino's Pizza  Crunchy Thin Crust  Cheeses Pizza  $5.99

In [25]:
df=pd.concat([df,dummy],axis=1)

In [26]:
df.head()

,Company,Pizza Name,Type,Price,Large,"Large (14"")",Medium,"Medium (12"")",Mini,Personal,Small,"Small (10"")","X Large (16"")","X-Large (16"")"
0,Domino's Pizza,Hand Tossed,Cheeses Pizza,$5.99,0,0,0,0,0,0,0,1,0,0
1,Domino's Pizza,Hand Tossed,Cheeses Pizza,$7.99,0,0,0,1,0,0,0,0,0,0
2,Domino's Pizza,Hand Tossed,Cheeses Pizza,$9.99,0,1,0,0,0,0,0,0,0,0
3,Domino's Pizza,Handmade Pan,Cheeses Pizza,$7.99,0,0,0,1,0,0,0,0,0,0
4,Domino's Pizza,Crunchy Thin Crust,Cheeses Pizza,$5.99,0,0,0,0,0,0,0,1,0,0

# access in one technic another way

In [27]:
df=pd.read_csv('Pizza Data.csv')
df.head()

          Company          Pizza Name           Type          Size   Price
0  Domino's Pizza         Hand Tossed  Cheeses Pizza   Small (10")  $5.99
1  Domino's Pizza         Hand Tossed  Cheeses Pizza  Medium (12")  $7.99
2  Domino's Pizza         Hand Tossed  Cheeses Pizza   Large (14")  $9.99
3  Domino's Pizza        Handmade Pan  Cheeses Pizza  Medium (12")  $7.99
4  Domino's Pizza  Crunchy Thin Crust  Cheeses Pizza   Small (10")  $5.99

In [28]:
columns=['Size']
for column in columns:
    one=pd.get_dummies(df[column],drop_first=True)
    df=pd.concat((df,one),axis=1).drop(column,axis=1)

In [29]:
df.head()

,Company,Pizza Name,Type,Price,Large,"Large (14"")",Medium,"Medium (12"")",Mini,Personal,Small,"Small (10"")","X Large (16"")","X-Large (16"")"
0,Domino's Pizza,Hand Tossed,Cheeses Pizza,$5.99,0,0,0,0,0,0,0,1,0,0
1,Domino's Pizza,Hand Tossed,Cheeses Pizza,$7.99,0,0,0,1,0,0,0,0,0,0
2,Domino's Pizza,Hand Tossed,Cheeses Pizza,$9.99,0,1,0,0,0,0,0,0,0,0
3,Domino's Pizza,Handmade Pan,Cheeses Pizza,$7.99,0,0,0,1,0,0,0,0,0,0
4,Domino's Pizza,Crunchy Thin Crust,Cheeses Pizza,$5.99,0,0,0,0,0,0,0,1,0,0

# Ordinal Encoder

In [30]:
from sklearn.preprocessing import OrdinalEncoder
df=pd.read_csv('Pizza Data.csv')

In [31]:
df.head()

          Company          Pizza Name           Type          Size   Price
0  Domino's Pizza         Hand Tossed  Cheeses Pizza   Small (10")  $5.99
1  Domino's Pizza         Hand Tossed  Cheeses Pizza  Medium (12")  $7.99
2  Domino's Pizza         Hand Tossed  Cheeses Pizza   Large (14")  $9.99
3  Domino's Pizza        Handmade Pan  Cheeses Pizza  Medium (12")  $7.99
4  Domino's Pizza  Crunchy Thin Crust  Cheeses Pizza   Small (10")  $5.99

In [32]:
df['Size'].unique()

array(['Small (10")', 'Medium (12")', 'Large (14")', 'X-Large (16")',
       'Medium', 'Large', 'Personal', 'Small', 'Mini', 'Jumbo',
       'X Large (16")'], dtype=object)

In [33]:
All_over_pizza_size=['Small (10")', 'Medium (12")', 'Large (14")', 'X-Large (16")',
       'Medium', 'Large', 'Personal', 'Small', 'Mini', 'Jumbo',
       'X Large (16")']

In [34]:
ordinal=OrdinalEncoder(categories=[All_over_pizza_size])
encoded=ordinal.fit_transform(df[['Size']])

In [35]:
encoded

array([[ 0.],
       [ 1.],
       [ 2.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 2.],
       [ 2.],
       [ 3.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 0.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 4.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 4.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 4.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 4.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 4.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 4.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 4.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 4.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 4.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 4.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 4.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 4.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 5.],
       [ 5.],
       [ 5.],
       [ 5.],
       [ 7.],
       [ 8.],
       [ 7.],
       [ 4.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 9.],
       [ 8.],
       [ 7.],
       [ 4.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 8.],
       [ 7.],
       [ 4.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 9.],
       [ 8.],
       [ 7.],
       [ 4.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 9.],
       [ 8.],
       [ 7.],
       [ 4.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 9.],
       [ 8.],
       [ 7.],
       [ 4.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 9.],
       [ 8.],
       [ 7.],
       [ 4.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 9.],
       [ 8.],
       [ 7.],
       [ 4.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 9.],
       [ 8.],
       [ 7.],
       [ 4.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 9.],
       [ 8.],
       [ 7.],
       [ 4.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 9.],
       [ 8.],
       [ 7.],
       [ 4.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 9.],
       [ 7.],
       [ 4.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 9.],
       [ 7.],
       [ 4.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 9.],
       [ 7.],
       [ 4.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 9.],
       [ 7.],
       [ 4.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 9.],
       [ 7.],
       [ 4.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 9.],
       [ 8.],
       [ 7.],
       [ 4.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 9.],
       [ 8.],
       [ 7.],
       [ 4.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 9.],
       [ 4.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 8.],
       [ 7.],
       [ 4.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 9.],
       [ 0.],
       [ 1.],
       [ 2.],
       [10.],
       [ 0.],
       [ 1.],
       [ 2.],
       [10.],
       [ 0.],
       [ 1.],
       [ 2.],
       [10.],
       [ 0.],
       [ 1.],
       [ 2.],
       [10.],
       [ 0.],
       [ 1.],
       [ 2.],
       [10.],
       [ 0.],
       [ 1.],
       [ 2.],
       [10.]])

In [36]:
encoded_size=pd.DataFrame(encoded,columns=["Encoded"])

In [37]:
encoded_size

     Encoded
0        0.0
1        1.0
2        2.0
3        1.0
4        0.0
..       ...
366     10.0
367      0.0
368      1.0
369      2.0
370     10.0

[371 rows x 1 columns]

In [38]:
df.Size=encoded_size

In [39]:
df.Size

0       0.0
1       1.0
2       2.0
3       1.0
4       0.0
       ...
366    10.0
367     0.0
368     1.0
369     2.0
370    10.0
Name: Size, Length: 371, dtype: float64

# Access in one technic

In [40]:
df=pd.read_csv("Pizza Data.csv")
df.head()

          Company          Pizza Name           Type          Size   Price
0  Domino's Pizza         Hand Tossed  Cheeses Pizza   Small (10")  $5.99
1  Domino's Pizza         Hand Tossed  Cheeses Pizza  Medium (12")  $7.99
2  Domino's Pizza         Hand Tossed  Cheeses Pizza   Large (14")  $9.99
3  Domino's Pizza        Handmade Pan  Cheeses Pizza  Medium (12")  $7.99
4  Domino's Pizza  Crunchy Thin Crust  Cheeses Pizza   Small (10")  $5.99

In [41]:
columns=['Size']
for col in columns:
    uniques=df[col].unique()
    df[col]=OrdinalEncoder(categories=[uniques ]).fit_transform(df[[col]])

In [42]:
df.head()

          Company          Pizza Name           Type  Size   Price
0  Domino's Pizza         Hand Tossed  Cheeses Pizza   0.0  $5.99
1  Domino's Pizza         Hand Tossed  Cheeses Pizza   1.0  $7.99
2  Domino's Pizza         Hand Tossed  Cheeses Pizza   2.0  $9.99
3  Domino's Pizza        Handmade Pan  Cheeses Pizza   1.0  $7.99
4  Domino's Pizza  Crunchy Thin Crust  Cheeses Pizza   0.0  $5.99

In [44]:
data_set=pd.read_csv("Pizza Data.csv")
data_set.info

<bound method DataFrame.info of             Company           Pizza Name              Type           Size  \
0    Domino's Pizza          Hand Tossed     Cheeses Pizza    Small (10")
1    Domino's Pizza          Hand Tossed     Cheeses Pizza   Medium (12")
2    Domino's Pizza          Hand Tossed     Cheeses Pizza    Large (14")
3    Domino's Pizza         Handmade Pan     Cheeses Pizza   Medium (12")
4    Domino's Pizza   Crunchy Thin Crust     Cheeses Pizza    Small (10")
..              ...                  ...               ...            ...
366     IMO's Pizza    BBQ Chicken Pizza  Specialty Pizzas  X Large (16")
367     IMO's Pizza  Egg-Ceptional Pizza  Specialty Pizzas    Small (10")
368     IMO's Pizza  Egg-Ceptional Pizza  Specialty Pizzas   Medium (12")
369     IMO's Pizza  Egg-Ceptional Pizza  Specialty Pizzas    Large (14")
370     IMO's Pizza  Egg-Ceptional Pizza  Specialty Pizzas  X Large (16")

       Price
0     $5.99
1     $7.99
2     $9.99
3     $7.99
4     $5.99
..       ...
366  $23.85
367  $11.80
368  $14.95
369  $18.65
370  $22.30

[371 rows x 5 columns]>

In [45]:
data_set.isnull().sum()

Company       0
Pizza Name    0
Type          0
Size          0
Price         0
dtype: int64

In [46]:
data_set.isnull

<bound method DataFrame.isnull of             Company           Pizza Name              Type           Size  \
0    Domino's Pizza          Hand Tossed     Cheeses Pizza    Small (10")
1    Domino's Pizza          Hand Tossed     Cheeses Pizza   Medium (12")
2    Domino's Pizza          Hand Tossed     Cheeses Pizza    Large (14")
3    Domino's Pizza         Handmade Pan     Cheeses Pizza   Medium (12")
4    Domino's Pizza   Crunchy Thin Crust     Cheeses Pizza    Small (10")
..              ...                  ...               ...            ...
366     IMO's Pizza    BBQ Chicken Pizza  Specialty Pizzas  X Large (16")
367     IMO's Pizza  Egg-Ceptional Pizza  Specialty Pizzas    Small (10")
368     IMO's Pizza  Egg-Ceptional Pizza  Specialty Pizzas   Medium (12")
369     IMO's Pizza  Egg-Ceptional Pizza  Specialty Pizzas    Large (14")
370     IMO's Pizza  Egg-Ceptional Pizza  Specialty Pizzas  X Large (16")

       Price
0     $5.99
1     $7.99
2     $9.99
3     $7.99
4     $5.99
..       ...
366  $23.85
367  $11.80
368  $14.95
369  $18.65
370  $22.30

[371 rows x 5 columns]>

In [48]:
data_set['Pizza Name'].unique()#Label Encoding

array(['Hand Tossed', 'Handmade Pan', 'Crunchy Thin Crust',
       'Brooklyn Style', 'Gluten Free Crust',
       'Spinach & Feta (Hand Tossed or Thin Crust)',
       'Spinach & Feta (Hand Tossed, Handmade Pan or Thin Crust)',
       'Spinach & Feta (Hand Tossed, Thin Crust or Brooklyn Style)',
       'Spinach & Feta (Brooklyn Style)',
       'Spinach & Feta (Gluten Free Crust)',
       'Wisconsin 6 Cheese (Hand Tossed or Thin Crust)',
       'Wisconsin 6 Cheese (Hand Tossed, Handmade Pan or Thin Crust)',
       'Wisconsin 6 Cheese (Hand Tossed, Thin Crust or Brooklyn Style)',
       'Wisconsin 6 Cheese (Brooklyn Style)',
       'Wisconsin 6 Cheese (Gluten Free Crust)',
       'Honolulu Hawaiian (Hand Tossed or Thin Crust)',
       'Honolulu Hawaiian (Hand Tossed, Handmade Pan or Thin Crust)',
       'Honolulu Hawaiian (Hand Tossed, Thin Crust or Brooklyn Style)',
       'Honolulu Hawaiian (Brooklyn Style)',
       'Honolulu Hawaiian (Gluten Free Crust)',
       'Philly Cheese Steak (Hand Tossed or Thin Crust)',
       'Philly Cheese Steak (Hand Tossed, Handmade Pan or Thin Crust)',
       'Philly Cheese Steak (Hand Tossed, Thin Crust or Brooklyn Style)',
       'Philly Cheese Steak (Brooklyn Style)',
       'Philly Cheese Steak (Gluten Free Crust)',
       'Pacific Veggie (Hand Tossed or Thin Crust)',
       'Pacific Veggie (Hand Tossed, Handmade Pan or Thin Crust)',
       'Pacific Veggie (Hand Tossed, Thin Crust or Brooklyn Style)',
       'Pacific Veggie (Brooklyn Style)',
       'Pacific Veggie (Gluten Free Crust)',
       'Cali Chicken Bacon Ranch™ (Hand Tossed or Thin Crust)',
       'Cali Chicken Bacon Ranch™ (Hand Tossed, Handmade Pan or Thin Crust)',
       'Cali Chicken Bacon Ranch™ (Hand Tossed, Thin Crust or Brooklyn Style)',
       'Cali Chicken Bacon Ranch™ (Brooklyn Style)',
       'Cali Chicken Bacon Ranch™ (Gluten Free Crust)',
       'Fiery Hawaiian™ (Hand Tossed or Thin Crust)',
       'Fiery Hawaiian™ (Hand Tossed, Handmade Pan or Thin Crust)',
       'Fiery Hawaiian™ (Hand Tossed, Thin Crust or Brooklyn Style)',
       'Fiery Hawaiian™ (Brooklyn Style)',
       'Fiery Hawaiian™ (Gluten Free Crust)',
       'Buffalo Chicken (Hand Tossed or Thin Crust)',
       'Buffalo Chicken (Hand Tossed, Handmade Pan or Thin Crust)',
       'Buffalo Chicken (Hand Tossed, Thin Crust or Brooklyn Style)',
       'Buffalo Chicken (Brooklyn Style)',
       'Buffalo Chicken (Gluten Free Crust)',
       'Memphis BBQ Chicken (Hand Tossed or Thin Crust)',
       'Memphis BBQ Chicken (Hand Tossed, Hnadmade Pan or Thin Crust)',
       'Memphis BBQ Chicken (Hand Tossed, Thin Crust or Brooklyn Style)',
       'Memphis BBQ Chicken (Brooklyn Style)',
       'Memphis BBQ Chicken (Gluten Free Crust)',
       "America's Favorite Feast® (Hand Tossed or Thin Crust)",
       "America's Favorite Feast® (Handmade Pan)",
       "America's Favorite Feast® (Hand Tossed, Thin Crust or Brooklyn Style)",
       "America's Favorite Feast® (Brooklyn Style)",
       "America's Favorite Feast® (Gluten Free Crust)",
       'Bacon Cheeseburger Feast® (Hand Tossed or Thin Crust)',
       'Bacon Cheeseburger Feast® (Handmade Pan)',
       'Bacon Cheeseburger Feast® (Hand Tossed, Thin Crust or Brooklyn Style)',
       'Bacon Cheeseburger Feast® (Brooklyn Style)',
       'Bacon Cheeseburger Feast® (Gluten Free Crust)',
       'Deluxe Feast® (Hand Tossed or Thin Crust)',
       'Deluxe Feast® (Handmade Pan)',
       'Deluxe Feast® (Hand Tossed, Thin Crust or Brooklyn Style)',
       'Deluxe Feast® (Brooklyn Style)',
       'Deluxe Feast® (Gluten Free Crust)',
       'ExtravaganZZa Feast® (Hand Tossed or Thin Crust)',
       'ExtravaganZZa Feast® (Hand Tossed, Handmade Pan or Thin Crust)',
       'ExtravaganZZa Feast® (Hand Tossed, Thin Crust or Brooklyn Style)',
       'ExtravaganZZa Feast® (Brooklyn Style)',
       'ExtravaganZZa Feast® (Gluten Free Crust)',
       'MeatZZa Feast® (Hand Tossed or Thin Crust)',
       'MeatZZa Feast® (Hand Tossed, Handmade Pan or Thin Crust)',
       'MeatZZa Feast® (Hand Tossed, Thin Crust or Brooklyn Style)',
       'MeatZZa Feast® (Brooklyn Style)',
       'MeatZZa Feast® (Gluten Free Crust)',
       'Ultimate Pepperoni Feast™ (Hand Tossed or Thin Crust)',
       'Ultimate Pepperoni Feast™ (Hand Tossed, Handmade Pan or Thin Crust)',
       'Ultimate Pepperoni Feast™ (Hand Tossed, Thin Crust or Brooklyn Style)',
       'Ultimate Pepperoni Feast™ (Brooklyn Style)',
       'Ultimate Pepperoni Feast™ (Gluten Free Crust)', 'Hand-Tossed',
       'Pan Pizza', 'Thin N Crispy', 'Stuffed Crust', 'Skinny Slice',
       "Pepperoni Lover's® Pizza (Hand-Tossed)",
       "Pepperoni Lover's® Pizza (Pan Pizza)",
       "Pepperoni Lover's® Pizza (Thin N Crispy)",
       "Pepperoni Lover's® Pizza (Stuffed Crust)",
       "Pepperoni Lover's® Pizza (Skinny Slice)",
       "Meat Lover's® Pizza (Hand-Tossed)",
       "Meat Lover's® Pizza (Pan Pizza)",
       "Meat Lover's® Pizza (Thin N Crispy)",
       "Meat Lover's® Pizza (Stuffed Crust)",
       "Meat Lover's® Pizza (Skinny Slice)",
       "Ultimate Cheese Lover's Pizza (Hand-Tossed)",
       "Ultimate Cheese Lover's Pizza (Pan Pizza)",
       "Ultimate Cheese Lover's Pizza (Thin N Crispy)",
       "Ultimate Cheese Lover's Pizza (Stuffed Crust)",
       "Ultimate Cheese Lover's Pizza (Skinny Slice)",
       "Veggie Lover's® Pizza (Hand-Tossed)",
       "Veggie Lover's® Pizza (Pan Pizza)",
       "Veggie Lover's® Pizza (Thin N Crispy)",
       "Veggie Lover's® Pizza (Stuffed Crust)",
       "Veggie Lover's® Pizza (Skinny Slice)",
       'Supreme Pizza (Hand-Tossed)', 'Supreme Pizza (Pan Pizza)',
       'Supreme Pizza (Thin N Crispy)', 'Supreme Pizza (Stuffed Crust)',
       'Supreme Pizza (Skinny Slice)', "BBQ Lover's™ (Hand-Tossed)",
       "BBQ Lover's™ (Pan Pizza)", "BBQ Lover's™ (Thin N Crispy)",
       "BBQ Lover's™ (Stuffed Crust)", "BBQ Lover's™ (Skinny Slice)",
       'Chicken Supreme Pizza (Hand-Tossed)',
       'Chicken Supreme Pizza (Pan Pizza)',
       'Chicken Supreme Pizza (Thin N Crispy)',
       'Chicken Supreme Pizza (Stuffed Crust)',
       'Chicken Supreme Pizza (Skinny Slice)',
       'New Primo Meat Pizza (Hand-Tossed)',
       'New Primo Meat Pizza (Pan Pizza)',
       'New Primo Meat Pizza (Thin N Crispy)',
       'New Primo Meat Pizza (Stuffed Crust)',
       'New Primo Meat Pizza (Skinny Slice)',
       'Hawaiian Luau (Hand-Tossed)', 'Hawaiian Luau (Pan Pizza)',
       'Hawaiian Luau (Thin N Crispy)', 'Hawaiian Luau (Stuffed Crust)',
       'Hawaiian Luau (Skinny Slice)',
       'Super Supreme Pizza (Hand-Tossed)',
       'Super Supreme Pizza (Pan Pizza)',
       'Super Supreme Pizza (Thin N Crispy)',
       'Super Supreme Pizza (Stuffed Crust)',
       'Super Supreme Pizza (Skinny Slice)',
       'Garden Party™ (Thin N Crispy)',
       'Old Fashioned Meatbrawl™ (Pan Pizza)',
       'Cock-a-doodle Bacon™ (Hand-Tossed)',
       'Hot and Twisted™ (Hand-Tossed)', 'Pretzel Piggy™ (Hand-Tossed)',
       'BBQ Bacon Cheeseburger (Hand-Tossed)',
       'Giddy-Up BBQ Chicken™ (Hand-Tossed)',
       'Buffalo State of Mind™ (Hand-Tossed)',
       'Cherry Pepper Bombshell™ (Thin N Crispy)',
       '7-Alarm Fire™ (Hand-Tossed)', 'Skinny Beach™ (Skinny Slice)',
       'Skinny With A Kick™ (Skinny Slice)',
       'Skinny Italy (Skinny Slice)', 'Skinny Luau™ (Skinny Slice)',
       'Skinny Club™ (Skinny Slice)',
       'Create Your Own (Gluten-Free Crust)', 'Cheese (Original Crust)',
       'Cheese (Original or Golden Crust)',
       'Cheese (Original, Golden or Thin Crust)',
       'Cheese (Mozza-Loaded Crust)', 'Cheese (Original or Thin Crust)',
       'All-Meat Combo Pizza (Original Crust)',
       'All-Meat Combo Pizza (Original or Golden Crust)',
       'All-Meat Combo Pizza (Original, Golden or Thin Crust)',
       'All-Meat Combo Pizza (Mozza-Loaded Crust)',
       'Bacon Cheeseburger Pizza (Original Crust)',
       'Bacon Cheeseburger Pizza (Original or Golden Crust)',
       'Bacon Cheeseburger Pizza (Original, Golden or Thin Crust)',
       'Bacon Cheeseburger Pizza (Mozza-Loaded Crust)',
       'Bacon Cheeseburger Pizza (Original or Thin Crust)',
       'Taco Pie Pizza (Original Crust)',
       'Taco Pie Pizza (Original or Golden Crust)',
       'Taco Pie Pizza (Original, Golden or Thin Crust)',
       'Taco Pie Pizza (Mozza-Loaded Crust)',
       'Taco Pie Pizza (Original or Thin Crust)',
       'Classic Combo Pizza (Original Crust)',
       'Classic Combo Pizza (Original or Golden Crust)',
       'Classic Combo Pizza (Original, Golden or Thin Crust)',
       'Classic Combo Pizza (Mozza-Loaded Crust)',
       'Classic Combo Pizza (Original or Thin Crust)',
       'Humble Pie Pizza (Original Crust)',
       'Humble Pie Pizza (Original or Golden Crust)',
       'Humble Pie Pizza (Original, Golden or Thin Crust)',
       'Humble Pie Pizza (Mozza-Loaded Crust)',
       'Humble Pie Pizza (Original or Thin Crust)',
       'Veggie Pie Pizza (Original Crust)',
       'Veggie Pie Pizza (Original or Golden Crust)',
       'Veggie Pie Pizza (Original, Golden or Thin Crust)',
       'Veggie Pie Pizza (Mozza-Loaded Crust)',
       'Veggie Pie Pizza (Original or Thin Crust)',
       'Hot Stuff Pizza (Original Crust)',
       'Hot Stuff Pizza (Original or Golden Crust)',
       'Hot Stuff Pizza (Original, Golden or Thin Crust)',
       'Hot Stuff Pizza (Mozza-Loaded Crust)',
       'Hot Stuff Pizza (Original or Thin Crust)',
       'Hawaiian Pizza (Original Crust)',
       'Hawaiian Pizza (Original or Golden Crust)',
       'Hawaiian Pizza (Original, Golden or Thin Crust)',
       'Hawaiian Pizza (Mozza-Loaded Crust)',
       'Hawaiian Pizza (Original or Thin Crust)',
       'BLT Pizza (Original Crust)',
       'BLT Pizza (Original or Golden Crust)',
       'BLT Pizza (Original, Golden or Thin Crust)',
       'BLT Pizza (Mozza-Loaded Crust)',
       'BLT Pizza (Original or Thin Crust)',
       'Buffalo Chicken Pizza (Original Crust)',
       'Buffalo Chicken Pizza (Original or Golden Crust)',
       'Buffalo Chicken Pizza (Original, Golden or Thin Crust)',
       'Buffalo Chicken Pizza (Mozza-Loaded Crust)',
       'Buffalo Chicken Pizza (Original or Thin Crust)',
       'Super Combo Pizza (Original or Golden Crust)',
       'Super Combo Pizza (Original, Golden or Thin Crust)',
       'Super Combo Pizza (Mozza-Loaded Crust)',
       'Super Combo Pizza (Original or Thin Crust)',
       'Super Hawaiian Pizza (Original or Golden Crust)',
       'Super Hawaiian Pizza (Original, Golden or Thin Crust)',
       'Super Hawaiian Pizza (Mozza-Loaded Crust)',
       'Super Hawaiian Pizza (Original or Thin Crust)',
       'Super Taco Pizza (Original or Golden Crust)',
       'Super Taco Pizza (Original, Golden or Thin Crust)',
       'Super Taco Pizza (Mozza-Loaded Crust)',
       'Super Taco Pizza (Original or Thin Crust)',
       'The Don (Original or Golden Crust)',
       'The Don (Original, Golden or Thin Crust)',
       'The Don (Mozza-Loaded Crust)', 'The Don (Original or Thin Crust)',
       'Super Veggie Pizza (Original or Golden Crust)',
       'Super Veggie Pizza (Original, Golden or Thin Crust)',
       'Super Veggie Pizza (Mozza-Loaded Crust)',
       'Super Veggie Pizza (Original or Thin Crust)',
       'BBQ Bacon Cheeseburger Pizza (Original Crust)',
       'BBQ Bacon Cheeseburger Pizza (Original, Golden or Thin Crust)',
       'BBQ Bacon Cheeseburger Pizza (Mozza-Loaded Crust)',
       'Chipotle Chicken and Bacon Pizza (Original Crust)',
       'Chipotle Chicken and Bacon Pizza (Original, Golden or Thin Crust)',
       'Chipotle Chicken and Bacon Pizza (Mozza-Loaded Crust)',
       'Margherita Pizza (Original, Golden or Thin Crust)',
       'Margherita Pizza (Thin Crust)',
       'Margherita Chicken Pizza (Original, Golden or Thin Crust)',
       'Margherita Chicken Pizza (Thin Crust)', 'Thin Crust',
       'Original Crust', 'Original or Golden Crust',
       'Original, Golden or Thin Crust', 'Mozza-Loaded Crust',
       'Original or Thin Crust', 'Deluxe Pizza', 'Veggie Pizza',
       'Cheese Pizza', 'All Meat Pizza', 'BBQ Chicken Pizza',
       'Egg-Ceptional Pizza'], dtype=object)

In [49]:
data_set['Company'].unique()#Label Encoding

array(["Domino's Pizza", 'Pizza Hut', "Godfather's Pizza", "IMO's Pizza"],
      dtype=object)

In [50]:
data_set["Type"].unique()#Label Encoding

array(['Cheeses Pizza', 'Specialty Pizzas', 'Feast Pizzas',
       'Cheese Pizza', 'Classic Recipe Pizzas', 'New Recipe Pizzas',
       'Skinny Pizzas', 'Gluten-Free Pizzas', 'Express Favorites'],
      dtype=object)

In [52]:
data_set["Size"].unique()#Label Encoding

array(['Small (10")', 'Medium (12")', 'Large (14")', 'X-Large (16")',
       'Medium', 'Large', 'Personal', 'Small', 'Mini', 'Jumbo',
       'X Large (16")'], dtype=object)

In [53]:
data_set["Price"].unique()#Label Encoding

array(['$5.99 ', '$7.99 ', '$9.99 ', '$11.99 ', '$8.99 ', '$13.99 ',
       '$15.99 ', '$17.99 ', '$14.99 ', '$15.49 ', '$8.49 ', '$10.49 ',
       '$4.29 ', '$12.49 ', '$4.79 ', '$17.49 ', '$13.49 ', '$16.49 ',
       '$5.29 ', '$18.49 ', '$4.99 ', '$10.99 ', '$12.99 ', '$18.99 ',
       '$19.99 ', '$22.24 ', '$23.99 ', '$27.99 ', '$26.23 ', '$16.99 ',
       '$21.99 ', '$22.49 ', '$25.99 ', '$26.49 ', '$29.99 ', '$20.99 ',
       '$24.99 ', '$28.99 ', '$12.69 ', '$15.34 ', '$15.24 ', '$18.69 ',
       '$18.74 ', '$12.70 ', '$16.20 ', '$19.95 ', '$23.85 ', '$9.30 ',
       '$11.60 ', '$14.45 ', '$17.35 ', '$19.20 ', '$11.80 ', '$14.95 ',
       '$18.65 ', '$22.30 '], dtype=object)